### ISSUE TITLE
Conflicted declarations error occured during compilation.

### ISSUE THREAD

**Issue by choikangjae** [gdh1995/vimium-c#852]
**What command or commands**

Was trying to compile it by myself and the commands are below.

```
git clone https://github.com/gdh1995/vimium-c.git
npm install typescript
npm install pngjs # only needed for Chromium-based browsers
node scripts/tsc
```

Everything worked by far but when I ran `gulp dist`, errors had occured.

```js
[22:14:46] dist/.build/background/ui_css.js
[22:14:46] dist/.build/background/utils.js
Warning: Found conflicted declarations with a same name: val; let val=toggleMap[key]  ###  let arr=toggle.slice(idx+1,-1).split("="),rawAttr=arr[0],val=arr[1]||"",op=rawAttr.slice(-1),isOnlyIncluded="*"===op,isWord="~"===op||isOnlyIncluded,attr=isWord?rawAttr.slice(0,-1):rawAttr,rawOld=attr_s(selected,attr),old=rawOld||"",valWord=isOnlyIncluded?val:" "+val+" ",oldWords=isOnlyIncluded?old:" "+old+" "
[22:14:49] 'min/content/_1' errored after 6.57 s
[22:14:49] Error: conflicted declarations!
    at testScopedLets (/mnt/c/Users/choik/Desktop/vimium/vimium-c/scripts/uglifyjs-mangle.js:382:13)
    at TreeWalker.visit (/mnt/c/Users/choik/Desktop/vimium/vimium-c/scripts/uglifyjs-mangle.js:322:29)
    at TreeWalker._visit (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:2979:24)
    at AST_Let._walk (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:1348:24)
    at walk_body (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:245:17)
    at AST_BlockStatement.<anonymous> (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:274:13)
    at TreeWalker._visit (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:2983:21)
    at AST_BlockStatement._walk (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:273:24)
    at AST_If.<anonymous> (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:1160:23)
    at TreeWalker._visit (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:2983:21)
[22:14:49] Saved nameCache for content
[22:14:49] '<anonymous>' errored after 8.15 s
[22:14:49] 'min/content' errored after 14 s
[22:14:49] 'manifest' errored after 14 s
[22:14:49] 'dist' errored after 29 s
```

<details>
<summary>Long Version of Stdout</summary>
<blockquote>
[22:14:35] Starting 'static'...
[22:14:35] Starting 'manifest'...
[22:14:35] Starting 'min/others'...
[22:14:35] Starting '<anonymous>'...
[22:14:35] Starting 'static/minify'...
[22:14:35] Starting 'min/pages'...
[22:14:35] Starting 'min/omni'...
[22:14:35] Starting 'min/misc'...
[22:14:35] Finished '<anonymous>' after 5.05 ms
[22:14:35] Starting 'static/minify-js'...
[22:14:35] Starting 'static/json'...
[22:14:35] Starting 'static/json2js'...
[22:14:35] Starting 'locales_en/json'...
[22:14:35] Starting 'minify-css'...
[22:14:35] Starting 'minify-html'...
[22:14:35] Starting 'min/content'...
[22:14:35] Starting 'min/bg'...
[22:14:35] Starting 'locales_en/json'...
[22:14:35] Starting 'min/omni/_1'...
[22:14:35] terser: last pass #2, seqences=30
[22:14:35] dist/.build/front/tee.js
[22:14:35] lib/math_parser.js
[22:14:39] _locales/en/messages.json
[22:14:39] _locales/en/messages.json
[22:14:39] _locales/fr/messages.json
[22:14:39] pages/options.css
[22:14:39] front/help_dialog.html
[22:14:39] i18n/en/options.js
[22:14:39] dist/.build/lib/injector.js
[22:14:40] lib/viewer.js
[22:14:40] _locales/zh_TW/messages.json
[22:14:40] pages/show.css
[22:14:40] front/vomnibar-tee.html
[22:14:40] i18n/fr/options.js
[22:14:40] dist/.build/front/vomnibar.js
[22:14:40] Finished 'locales_en/json' after 5.33 s
[22:14:41] dist/.build/lib/simple_eval.js
[22:14:41] background/worker.js
[22:14:41] Finished 'locales_en/json' after 5.88 s
[22:14:41] Starting '<anonymous>'...
[22:14:41] _locales/zh_CN/messages.json
[22:14:41] pages/blank.html
[22:14:41] lib/viewer.css
[22:14:41] i18n/zh/options.js
[22:14:41] dist/.build/pages/define.js
[22:14:41] Finished 'min/omni/_1' after 5.94 s
[22:14:41] Saved nameCache for omni
[22:14:41] Finished 'min/omni' after 6.01 s
[22:14:41] pages/options.html
[22:14:41] _locales/zh/messages.json
[22:14:41] i18n/fr/popup.js
[22:14:41] dist/.build/pages/loader.js
[22:14:41] settings-template.json
[22:14:41] pages/popup.html
[22:14:41] Finished 'static/minify-js' after 6.1 s
[22:14:41] i18n/zh/popup.js
[22:14:41] Finished 'minify-css' after 6.1 s
[22:14:41] pages/show.html
[22:14:41] i18n/en/background.json
[22:14:41] i18n/en/popup.js
[22:14:41] i18n/en/help_dialog.json
[22:14:41] background/worker.html
[22:14:41] Finished 'min/misc' after 6.13 s
[22:14:41] i18n/zh/background.json
[22:14:41] Starting 'min/pages/_1'...
[22:14:41] i18n/zh/help_dialog.json
[22:14:41] Finished 'static/json2js' after 6.15 s
[22:14:41] i18n/fr/background.json
[22:14:41] dist/.build/pages/options_base.js
[22:14:41] Finished 'minify-html' after 6.36 s
[22:14:41] dist/.build/pages/options_checker.js
[22:14:41] i18n/fr/help_dialog.json
[22:14:41] dist/.build/pages/options_defs.js
[22:14:42] dist/.build/pages/options_ext.js
[22:14:42] dist/.build/pages/options_permissions.js
[22:14:42] dist/.build/pages/options_popup.js
[22:14:42] dist/.build/pages/options_wnd.js
[22:14:42] dist/.build/pages/show.js
[22:14:42] Finished 'static/json' after 7.25 s
[22:14:42] Finished 'static/minify' after 7.25 s
[22:14:42] Starting '<anonymous>'...
[22:14:42] Starting 'png2bin'...
[22:14:42] Finished 'png2bin' after 48 ms
[22:14:42] dist/.build/pages/async_bg.js
[22:14:42] front/vimium-c.css
[22:14:42] Finished 'min/pages/_1' after 1.33 s
[22:14:42] Saved nameCache for pages
[22:14:42] Finished 'min/pages' after 7.47 s
[22:14:42] Finished 'min/others' after 7.47 s
[22:14:42] Starting 'min/content/_1'...
[22:14:42] front/vomnibar.html
[22:14:42] dist/.build/lib/env.js
[22:14:42] Finished '<anonymous>' after 342 ms
[22:14:42] Finished 'static' after 7.6 s
[22:14:42] dist/.build/lib/utils.js
[22:14:42] Starting 'min/bg/_1'...
[22:14:42] dist/.build/lib/keyboard_utils.js
[22:14:42] dist/.build/background/action_icon.js
[22:14:42] dist/.build/lib/dom_utils.js
[22:14:43] dist/.build/background/all_commands.js
[22:14:43] dist/.build/lib/rect.js
[22:14:43] dist/.build/background/browser.js
[22:14:43] dist/.build/content/dom_ui.js
[22:14:43] dist/.build/background/browsing_data_manager.js
[22:14:43] dist/.build/content/async_dispatcher.js
[22:14:43] dist/.build/background/clipboard.js
[22:14:43] dist/.build/content/hud.js
[22:14:43] dist/.build/background/completion.js
[22:14:43] dist/.build/content/insert.js
[22:14:43] dist/.build/background/completion_utils.js
[22:14:43] dist/.build/content/key_handler.js
[22:14:43] dist/.build/background/define.js
[22:14:43] dist/.build/background/eval_urls.js
[22:14:43] dist/.build/content/port.js
[22:14:44] dist/.build/background/exclusions.js
[22:14:44] dist/.build/content/pagination.js
[22:14:44] dist/.build/background/filter_tabs.js
[22:14:44] dist/.build/content/marks.js
[22:14:44] dist/.build/background/frame_commands.js
[22:14:44] dist/.build/background/help_dialog.js
[22:14:44] dist/.build/content/local_links.js
[22:14:44] dist/.build/background/i18n.js
[22:14:44] dist/.build/content/hint_filters.js
[22:14:44] dist/.build/background/key_mappings.js
[22:14:44] dist/.build/content/link_actions.js
[22:14:44] dist/.build/background/main.js
[22:14:44] dist/.build/background/normalize_urls.js
[22:14:44] dist/.build/content/link_hints.js
[22:14:44] dist/.build/background/open_urls.js
[22:14:44] dist/.build/content/omni.js
[22:14:44] dist/.build/background/others.js
[22:14:44] dist/.build/content/mode_find.js
[22:14:45] dist/.build/background/page_handlers.js
[22:14:45] dist/.build/background/parse_urls.js
[22:14:45] dist/.build/content/visual.js
[22:14:45] dist/.build/background/ports.js
[22:14:45] dist/.build/content/scroller.js
[22:14:45] dist/.build/background/request_handlers.js
[22:14:45] dist/.build/background/run_commands.js
[22:14:45] dist/.build/content/request_handlers.js
[22:14:45] dist/.build/background/run_keys.js
[22:14:45] dist/.build/content/commands.js
[22:14:45] dist/.build/background/settings.js
[22:14:45] dist/.build/background/store.js
[22:14:45] dist/.build/content/extend_click_mv2.js
[22:14:45] dist/.build/background/sync.js
[22:14:45] dist/.build/content/extend_click_ff.js
[22:14:46] dist/.build/background/tab_commands.js
[22:14:46] dist/.build/content/frontend.js
[22:14:46] dist/.build/background/tools.js
[22:14:46] dist/.build/background/ui_css.js
[22:14:46] dist/.build/background/utils.js
Warning: Found conflicted declarations with a same name: val; let val=toggleMap[key]  ###  let arr=toggle.slice(idx+1,-1).split("="),rawAttr=arr[0],val=arr[1]||"",op=rawAttr.slice(-1),isOnlyIncluded="*"===op,isWord="~"===op||isOnlyIncluded,attr=isWord?rawAttr.slice(0,-1):rawAttr,rawOld=attr_s(selected,attr),old=rawOld||"",valWord=isOnlyIncluded?val:" "+val+" ",oldWords=isOnlyIncluded?old:" "+old+" "
[22:14:49] 'min/content/_1' errored after 6.57 s
[22:14:49] Error: conflicted declarations!
    at testScopedLets (/mnt/c/Users/choik/Desktop/vimium/vimium-c/scripts/uglifyjs-mangle.js:382:13)
    at TreeWalker.visit (/mnt/c/Users/choik/Desktop/vimium/vimium-c/scripts/uglifyjs-mangle.js:322:29)
    at TreeWalker._visit (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:2979:24)
    at AST_Let._walk (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:1348:24)
    at walk_body (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:245:17)
    at AST_BlockStatement.<anonymous> (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:274:13)
    at TreeWalker._visit (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:2983:21)
    at AST_BlockStatement._walk (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:273:24)
    at AST_If.<anonymous> (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:1160:23)
    at TreeWalker._visit (file:///mnt/c/Users/choik/Desktop/vimium/vimium-c/node_modules/terser/lib/ast.js:2983:21)
[22:14:49] Saved nameCache for content
[22:14:49] '<anonymous>' errored after 8.15 s
[22:14:49] 'min/content' errored after 14 s
[22:14:49] 'manifest' errored after 14 s
[22:14:49] 'dist' errored after 29 s
</blockquote></details>

**How should a feature do**

Since the messages are telling quite much so I tried to figure it out on my own, but I couldn't.
Am I doing something wrong?

**Comment by gdh1995** [comment]
Hello I've fixed it and you may pull a latest commit and retry `gulp dist`.

**Comment by choikangjae** [comment]
Thank you so much for your help! Now it works like a charm. And thaks again for customizing this extension. It prvides me the features what exactly that I wanted. :)
